import {cloudflare} from "@cloudflare/vite-plugin";
import tailwindcss from "@tailwindcss/vite";
import {devtools} from "@tanstack/devtools-vite";
import {tanstackStart} from "@tanstack/react-start/plugin/vite";
import viteReact from "@vitejs/plugin-react";
import {defineConfig} from "vite-plus";

const config = defineConfig({
  staged: {"*": "vp fmt --no-error-on-unmatched-pattern"},
  fmt: {
    arrowParens: "avoid",
    bracketSpacing: false,
    bracketSameLine: true,
    embeddedLanguageFormatting: "auto",
    sortImports: true,
    sortTailwindcss: true,
    jsxSingleQuote: false,
    objectWrap: "collapse",
    quoteProps: "as-needed",
    tabWidth: 2,
    trailingComma: "es5",
  },
  lint: {
    // No react-perf plugin: React Compiler (see `viteReact({compiler: true})`) memoizes inline
    // functions/objects/JSX props, which is what those rules guard against.
    plugins: ["unicorn", "typescript", "oxc", "react", "jsx-a11y", "import", "promise"],
    categories: {correctness: "warn", suspicious: "warn", perf: "warn"},
    rules: {
      // Automatic JSX runtime: React doesn't need to be in scope.
      "react/react-in-jsx-scope": "off",
      // TanStack Form's documented API is `<form.Field children={field => ...} />`.
      "react/no-children-prop": "off",
      // Autofocus on HeroUI components (e.g. a dialog's first field when it opens) is intended UX.
      "jsx-a11y/no-autofocus": ["warn", {ignoreNonDOM: true}],
      "for-direction": "warn",
      "no-async-promise-executor": "warn",
      "no-caller": "warn",
      "no-class-assign": "warn",
      "no-compare-neg-zero": "warn",
      "no-cond-assign": "warn",
      "no-const-assign": "warn",
      "no-constant-binary-expression": "warn",
      "no-constant-condition": "warn",
      "no-control-regex": "warn",
      "no-debugger": "warn",
      "no-delete-var": "warn",
      "no-dupe-class-members": "warn",
      "no-dupe-else-if": "warn",
      "no-dupe-keys": "warn",
      "no-duplicate-case": "warn",
      "no-empty-character-class": "warn",
      "no-empty-pattern": "warn",
      "no-empty-static-block": "warn",
      "no-eval": "warn",
      "no-ex-assign": "warn",
      "no-extra-boolean-cast": "warn",
      "no-func-assign": "warn",
      "no-global-assign": "warn",
      "no-import-assign": "warn",
      "no-invalid-regexp": "warn",
      "no-irregular-whitespace": "warn",
      "no-loss-of-precision": "warn",
      "no-new-native-nonconstructor": "warn",
      "no-nonoctal-decimal-escape": "warn",
      "no-obj-calls": "warn",
      "no-self-assign": "warn",
      "no-setter-return": "warn",
      "no-shadow-restricted-names": "warn",
      "no-sparse-arrays": "warn",
      "no-this-before-super": "warn",
      "no-unassigned-vars": "warn",
      "no-unsafe-finally": "warn",
      "no-unsafe-negation": "warn",
      "no-unsafe-optional-chaining": "warn",
      "no-unused-expressions": "warn",
      "no-unused-labels": "warn",
      "no-unused-private-class-members": "warn",
      "no-unused-vars": "warn",
      "no-useless-backreference": "warn",
      "no-useless-catch": "warn",
      "no-useless-escape": "warn",
      "no-useless-rename": "warn",
      "no-with": "warn",
      "require-yield": "warn",
      "use-isnan": "warn",
      "valid-typeof": "warn",
      "oxc/bad-array-method-on-arguments": "warn",
      "oxc/bad-char-at-comparison": "warn",
      "oxc/bad-comparison-sequence": "warn",
      "oxc/bad-min-max-func": "warn",
      "oxc/bad-object-literal-comparison": "warn",
      "oxc/bad-replace-all-arg": "warn",
      "oxc/const-comparisons": "warn",
      "oxc/double-comparisons": "warn",
      "oxc/erasing-op": "warn",
      "oxc/missing-throw": "warn",
      "oxc/number-arg-out-of-range": "warn",
      "oxc/only-used-in-recursion": "warn",
      "oxc/uninvoked-array-callback": "warn",
      "typescript/await-thenable": "warn",
      "typescript/no-array-delete": "warn",
      "typescript/no-base-to-string": "warn",
      "typescript/no-duplicate-enum-values": "warn",
      "typescript/no-duplicate-type-constituents": "warn",
      "typescript/no-extra-non-null-assertion": "warn",
      "typescript/no-floating-promises": "warn",
      "typescript/no-for-in-array": "warn",
      "typescript/no-implied-eval": "warn",
      "typescript/no-meaningless-void-operator": "warn",
      "typescript/no-misused-new": "warn",
      "typescript/no-misused-spread": "warn",
      "typescript/no-non-null-asserted-optional-chain": "warn",
      "typescript/no-redundant-type-constituents": "warn",
      "typescript/no-this-alias": "warn",
      "typescript/unbound-method": "off",
      "typescript/no-unnecessary-parameter-property-assignment": "warn",
      "typescript/no-unsafe-declaration-merging": "warn",
      "typescript/no-unsafe-unary-minus": "warn",
      "typescript/no-useless-empty-export": "warn",
      "typescript/no-wrapper-object-types": "warn",
      "typescript/prefer-as-const": "warn",
      "typescript/require-array-sort-compare": "warn",
      "typescript/restrict-template-expressions": "warn",
      "typescript/triple-slash-reference": "warn",
      "unicorn/no-await-in-promise-methods": "warn",
      "unicorn/no-empty-file": "warn",
      "unicorn/no-invalid-fetch-options": "warn",
      "unicorn/no-invalid-remove-event-listener": "warn",
      "unicorn/no-new-array": "warn",
      "unicorn/no-single-promise-in-promise-methods": "warn",
      "unicorn/no-thenable": "warn",
      "unicorn/no-unnecessary-await": "warn",
      "unicorn/no-useless-fallback-in-spread": "warn",
      "unicorn/no-useless-length-check": "warn",
      "unicorn/no-useless-spread": "warn",
      "unicorn/prefer-set-size": "warn",
      "unicorn/prefer-string-starts-ends-with": "warn",
      "vite-plus/prefer-vite-plus-imports": "error",
    },
    settings: {
      "jsx-a11y": {components: {}, attributes: {}},
      next: {rootDir: []},
      react: {formComponents: [], linkComponents: []},
      jsdoc: {
        ignorePrivate: false,
        ignoreInternal: false,
        ignoreReplacesDocs: true,
        overrideReplacesDocs: true,
        augmentsExtendsReplacesDocs: false,
        implementsReplacesDocs: false,
        exemptDestructuredRootsFromChecks: false,
        tagNamePreference: {},
      },
      vitest: {typecheck: false},
    },
    env: {builtin: true},
    globals: {},
    ignorePatterns: [],
    options: {typeAware: true, typeCheck: true},
    jsPlugins: [{name: "vite-plus", specifier: "vite-plus/oxlint-plugin"}],
  },
  resolve: {tsconfigPaths: true},
  plugins: [
    devtools(),
    cloudflare({viteEnvironment: {name: "ssr"}}),
    tailwindcss(),
    tanstackStart(),
    viteReact({compiler: true}),
  ],
  build: {sourcemap: true},
  optimizeDeps: {exclude: ["@tanstack/start-server-core"]},
  ssr: {optimizeDeps: {exclude: ["@tanstack/start-server-core"]}},
});

export default config;
