// Generated by Wrangler by running `wrangler types --x-include-runtime -e local`

interface Env {
	NODE_VERSION: "22";
	TURSO_URL: "http://db:8080";
	TURSO_AUTH_TOKEN: "";
	KINDE_CLIENT_ID: string;
	KINDE_CLIENT_SECRET: string;
	VITE_GOOGLE_API_CLIENT_ID: string;
	GOOGLE_API_CLIENT_SECRET: string;
	VITE_GOOGLE_API_KEY: string;
	DISCORD_BOT_TOKEN: string;
	VITE_DISCORD_CLIENT_ID: string;
	SENTRY_AUTH_TOKEN: string;
	CHAT_ROOMS: DurableObjectNamespace<import("./src/index").ChatRoom>;
	NOTIFICATION_ROOMS: DurableObjectNamespace<import("./src/index").NotificationRoom>;
	PRESENCE_ROOMS: DurableObjectNamespace<import("./src/index").PresenceRoom>;
	DISCORD_CLIENT: DurableObjectNamespace<import("./src/index").DiscordClient>;
	ASSETS: Fetcher;
}
