// Generated by Wrangler on Wed Sep 04 2024 17:36:01 GMT+0800 (China Standard Time)
// by running `wrangler types`

interface Env {
	ROOMS: DurableObjectNamespace<import('./src/index').ChatRoom>;
	DISCORD_BOT_TOKEN: string;
}
