-- One-off: reconcile a D1 database created by drizzle-kit 0.31 with the drizzle-kit 1.0 schema,
-- and add the missing foreign-key indexes. Afterwards `drizzle-kit push --explain` reports no
-- changes.
--
-- drizzle-kit 1.0 models `.unique()` as an inline UNIQUE constraint, so `user` and `session` must be
-- rebuilt. On D1 foreign keys can't be disabled, and `DROP TABLE user` cascade-deletes every row
-- that references it (session, account, member, invitation, activity_log_entry and the three
-- *_activity_log_entry tables). This script snapshots those rows, rebuilds, then restores them.
-- Foreign keys are deferred, so they are checked once at the end; any violation aborts the whole
-- script.
--
-- D1 runs a --file atomically: if anything fails (including the final foreign-key check) the whole
-- script is rolled back. Runbook (production, during downtime so nothing writes in between):
--
--   1. Must return no rows (orphans would make the final check fail and roll back):
--      pnpm exec wrangler d1 execute wow-production --env production --remote --command "PRAGMA foreign_key_check"
--   2. Rollback point:
--      pnpm exec wrangler d1 time-travel info wow-production --env production
--      pnpm exec wrangler d1 export wow-production --env production --remote --output backup-before-reconcile.sql
--   3. Apply:
--      pnpm exec wrangler d1 execute wow-production --env production --remote --file scripts/2026-10-01-d1-reconcile-schema.sql
--   4. Verify: step 1 again (no rows), and `CLOUDFLARE_ENV=production pnpm exec drizzle-kit push --explain`
--      should report "No changes detected".
--   Undo: pnpm exec wrangler d1 time-travel restore wow-production --env production --bookmark=<from step 2>

PRAGMA defer_foreign_keys = true;

-- 1. Snapshot every row the `user` rebuild would cascade-delete.
CREATE TABLE `_bk_session` AS SELECT * FROM `session`;
CREATE TABLE `_bk_account` AS SELECT * FROM `account`;
CREATE TABLE `_bk_member` AS SELECT * FROM `member`;
CREATE TABLE `_bk_invitation` AS SELECT * FROM `invitation`;
CREATE TABLE `_bk_activity_log_entry` AS SELECT * FROM `activity_log_entry`;
CREATE TABLE `_bk_round_activity_log_entry` AS SELECT * FROM `round_activity_log_entry`;
CREATE TABLE `_bk_puzzle_activity_log_entry` AS SELECT * FROM `puzzle_activity_log_entry`;
CREATE TABLE `_bk_workspace_activity_log_entry` AS SELECT * FROM `workspace_activity_log_entry`;

-- 2. Rebuild `user` (DDL as generated by drizzle-kit 1.0).
CREATE TABLE `__new_user` (
	`id` text PRIMARY KEY,
	`name` text NOT NULL,
	`email` text NOT NULL UNIQUE,
	`email_verified` integer DEFAULT false NOT NULL,
	`image` text,
	`created_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	`updated_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	`notifications_disabled` integer DEFAULT false
);
INSERT INTO `__new_user`(`id`, `name`, `email`, `email_verified`, `image`, `created_at`, `updated_at`, `notifications_disabled`) SELECT `id`, `name`, `email`, `email_verified`, `image`, `created_at`, `updated_at`, `notifications_disabled` FROM `user`;
DROP TABLE `user`;
ALTER TABLE `__new_user` RENAME TO `user`;

-- 3. Rebuild `session` from its snapshot (the drop above emptied it).
CREATE TABLE `__new_session` (
	`id` text PRIMARY KEY,
	`expires_at` integer NOT NULL,
	`token` text NOT NULL UNIQUE,
	`created_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	`updated_at` integer NOT NULL,
	`ip_address` text,
	`user_agent` text,
	`user_id` text NOT NULL,
	`active_organization_id` text,
	CONSTRAINT `fk_session_user_id_user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON DELETE CASCADE
);
INSERT INTO `__new_session`(`id`, `expires_at`, `token`, `created_at`, `updated_at`, `ip_address`, `user_agent`, `user_id`, `active_organization_id`) SELECT `id`, `expires_at`, `token`, `created_at`, `updated_at`, `ip_address`, `user_agent`, `user_id`, `active_organization_id` FROM `_bk_session`;
DROP TABLE `session`;
ALTER TABLE `__new_session` RENAME TO `session`;
CREATE INDEX `session_userId_idx` ON `session` (`user_id`);

-- 4. Restore the cascade-deleted rows (parents before children).
DELETE FROM `account`;
INSERT INTO `account` SELECT * FROM `_bk_account`;
DELETE FROM `member`;
INSERT INTO `member` SELECT * FROM `_bk_member`;
DELETE FROM `invitation`;
INSERT INTO `invitation` SELECT * FROM `_bk_invitation`;
DELETE FROM `activity_log_entry`;
INSERT INTO `activity_log_entry` SELECT * FROM `_bk_activity_log_entry`;
DELETE FROM `round_activity_log_entry`;
INSERT INTO `round_activity_log_entry` SELECT * FROM `_bk_round_activity_log_entry`;
DELETE FROM `puzzle_activity_log_entry`;
INSERT INTO `puzzle_activity_log_entry` SELECT * FROM `_bk_puzzle_activity_log_entry`;
DELETE FROM `workspace_activity_log_entry`;
INSERT INTO `workspace_activity_log_entry` SELECT * FROM `_bk_workspace_activity_log_entry`;

DROP TABLE `_bk_session`;
DROP TABLE `_bk_account`;
DROP TABLE `_bk_member`;
DROP TABLE `_bk_invitation`;
DROP TABLE `_bk_activity_log_entry`;
DROP TABLE `_bk_round_activity_log_entry`;
DROP TABLE `_bk_puzzle_activity_log_entry`;
DROP TABLE `_bk_workspace_activity_log_entry`;

-- 5. Indexes: drop the duplicate slug index, add the foreign-key indexes.
DROP INDEX IF EXISTS `organization_slug_unique`;
CREATE INDEX `activity_log_entry_workspaceId_createdAt_idx` ON `activity_log_entry` (`workspaceId`,`createdAt`);
CREATE INDEX `activity_log_entry_userId_idx` ON `activity_log_entry` (`userId`);
CREATE INDEX `hunt_puzzles_huntId_idx` ON `hunt_puzzles` (`huntId`);
CREATE INDEX `puzzle_roundId_idx` ON `puzzle` (`roundId`);
CREATE INDEX `puzzle_parentPuzzleId_idx` ON `puzzle` (`parentPuzzleId`);
CREATE INDEX `puzzle_activity_log_entry_puzzleId_idx` ON `puzzle_activity_log_entry` (`puzzleId`);
CREATE INDEX `round_workspaceId_idx` ON `round` (`workspaceId`);
CREATE INDEX `round_activity_log_entry_roundId_idx` ON `round_activity_log_entry` (`roundId`);
