// Generated by Wrangler on Tue Sep 03 2024 14:00:59 GMT+0800 (China Standard Time)
// by running `wrangler types`

interface Env {
  BUN_VERSION: "1.1.26";
  DB: D1Database;
  CHAT_ROOMS: DurableObjectNamespace<import("../do/src/index").ChatRoom>;
  NOTIFICATION_ROOMS: DurableObjectNamespace<
    import("../do/src/index").NotificationRoom
  >;
  PRESENCE_ROOMS: DurableObjectNamespace<
    import("../do/src/index").PresenceRoom
  >;
  DISCORD_CLIENT: DurableObjectNamespace<
    import("../do/src/index").DiscordClient
  >;

  KINDE_CLIENT_ID: string;
  KINDE_CLIENT_SECRET: string;
  VITE_GOOGLE_API_KEY: string;
  VITE_GOOGLE_API_CLIENT_ID: string;
  GOOGLE_API_CLIENT_SECRET: string;
  TURSO_URL: string;
  TURSO_AUTH_TOKEN?: string;
  VITE_DISCORD_CLIENT_ID: string;
  DISCORD_CLIENT_SECRET: string;
  DISCORD_BOT_TOKEN: string;
}
